artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/05fc3a210cea43bc9ad202131613bf38/artifacts
end_time: 1728231211616
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 05fc3a210cea43bc9ad202131613bf38
run_name: Default
run_uuid: 05fc3a210cea43bc9ad202131613bf38
source_name: ''
source_type: 4
source_version: ''
start_time: 1728231211598
status: 3
tags: []
user_id: mle-user
