artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/f4abdc1b0e5c4921bbbf67b74230ce00/artifacts
end_time: 1728231754099
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f4abdc1b0e5c4921bbbf67b74230ce00
run_name: Default
run_uuid: f4abdc1b0e5c4921bbbf67b74230ce00
source_name: ''
source_type: 4
source_version: ''
start_time: 1728231754091
status: 3
tags: []
user_id: mle-user
